### ISSUE TITLE
Can't clone on Windows

### ISSUE THREAD

**Issue by elseLuna** [buzden/deptycheck#205]
Windows doesn't allow the following characters in file/folder names: `\ / : * ? " < > |`.
Several folders in `tests/derivation/core` contain a `>` in their name, preventing the repo from even being cloned on windows.

**Comment by buzden** [comment]
Right, we shall be more friendly in this regard

**Comment by buzden** [comment]
We've renamed those files. @elseLuna, please inform if something else goes wrong.

**Comment by elseLuna** [comment]
It all looks good, thanks.
